{% set name = "espaloma" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/espaloma/archive/{{ version }}.tar.gz
  sha256: 8f3f2481d949aa7f59759540815d4e7de1d6ff168efeb3ce818ea2b155d2428f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python =3.11
  run:
    - matplotlib-base
    - numpy
    - openff-forcefields
    - openff-toolkit >=0.12.0
    - openff-units
    - openmm
    - openmmforcefields >=0.11.2
    - pydantic <2
    - python >=3.9
    - pytorch
    - qcportal >=0.15.0,<0.50.0a0
    - scipy
    - smirnoff99Frosst
    - tqdm
  run_constrained:
    - dgl =1.1.2

test:
  imports:
    - espaloma
  commands:
    - pip check
    - pytest --pyargs espaloma
  requires:
    - pip
    - pytest

about:
  home: https://github.com/choderalab/espaloma
  summary: Extensible Surrogate Potential of Ab initio Learned and Optimized by Message-passing Algorithm ðŸ¹ https://arxiv.org/abs/2010.01196
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - yuanqing-wang
    - ijpulidos
    - jchodera
