{% set name = "espaloma" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/espaloma/archive/{{ version }}.tar.gz
  sha256: 8f3f2481d949aa7f59759540815d4e7de1d6ff168efeb3ce818ea2b155d2428f
  patches:
    - patches/0000-update-versioneer.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dgl >=1.1.2,<=2.3.0
    - matplotlib-base
    - numpy
    - openff-forcefields
    - openff-toolkit >=0.12.0
    - openff-units
    - openmm
    - openmmforcefields >=0.11.2
    - pydantic <2
    - python >={{ python_min }}
    - pytorch
    - qcportal >=0.15.0,<0.50.0a0
    - scipy
    - smirnoff99Frosst
    - tqdm
    - torchdata <=0.10.0

test:
  imports:
    - espaloma
  commands:
    - pytest --pyargs espaloma
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/choderalab/espaloma
  summary: Extensible Surrogate Potential of Ab initio Learned and Optimized by Message-passing Algorithm 🍹 https://arxiv.org/abs/2010.01196
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - yuanqing-wang
    - ijpulidos
    - jchodera
