{% set name = "espaloma" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/espaloma/archive/{{ version }}.tar.gz
  sha256: 9e5aff9e84638d2c7e34bf0da807a3935960df43c2b59c91c1a1945802991b52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dgl >=1.1.2,<=2.3.0
    - matplotlib-base
    - numpy
    - openff-amber-ff-ports >=2025.09.0  # https://github.com/conda-forge/openff-toolkit-feedstock/pull/117
    - openff-forcefields
    - openff-toolkit >=0.12.0
    - openff-units
    - openmm
    - openmmforcefields >=0.11.2
    - python >={{ python_min }}
    - pytorch
    - qcportal >=0.50
    - scipy
    - smirnoff99frosst >=1.1.0.1  # https://github.com/openforcefield/smirnoff99Frosst/issues/109 
    - tqdm
    - torchdata <0.10  # https://github.com/pytorch/data/issues/1196#issuecomment-2542528439

test:
  imports:
    - espaloma
  commands:
    - pytest --pyargs espaloma
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/choderalab/espaloma
  summary: Extensible Surrogate Potential of Ab initio Learned and Optimized by Message-passing Algorithm 🍹 https://arxiv.org/abs/2010.01196
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - yuanqing-wang
    - ijpulidos
    - jchodera
