{% set name = "espaloma" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/espaloma/archive/{{ version }}.tar.gz
  sha256: 8f3f2481d949aa7f59759540815d4e7de1d6ff168efeb3ce818ea2b155d2428f

build:
  number: 1

outputs:
  - name: espaloma-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python =3.11
      run:
        - python >=3.9
        - numpy
        - openff-forcefields
        - openff-toolkit >=0.12.0
        - openff-units
        - openmm
        - openmmforcefields >=0.11.2
        - pydantic <2
        - pytorch
        - qcportal =0.15
        - scipy
        - tqdm
    test:
      imports:
        - espaloma

  - name: espaloma
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
      run:
        - python >=3.9
        - matplotlib-base
        - dgl =1.1.2
        - {{ pin_subpackage('espaloma-base', exact=True) }}
    test:
      imports:
        - espaloma
      commands:
        - pip check
        - pytest --pyargs espaloma
      requires:
        - pip
        - pytest

about:
  home: https://github.com/choderalab/espaloma
  summary: Extensible Surrogate Potential of Ab initio Learned and Optimized by Message-passing Algorithm 🍹 https://arxiv.org/abs/2010.01196
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - yuanqing-wang
    - ijpulidos
    - jchodera
