{% set name = "espaloma" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/espaloma/archive/{{ version }}.tar.gz
  sha256: e538f41ed3799d402b770b42429ab2d976bce41ed0dcc93099821dfaaf2bef3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - openff-forcefields
    - openff-toolkit
    - openmm
    - openmmforcefields
    - python >=3.6
    - pytorch
    - qcportal >=0.15.0
    - scipy
    - smirnoff99Frosst
    - tqdm

test:
  imports:
    - espaloma
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/choderalab/espaloma
  summary: Extensible Surrogate Potential of Ab initio Learned and Optimized by Message-passing Algorithm 🍹 https://arxiv.org/abs/2010.01196
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
