{% set name = "espaloma" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/espaloma/archive/{{ version }}.tar.gz
  sha256: 6f468793fb82de91185e77e3205b1889e7365b98f48a362344c3f0fddac29aa5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - openff-forcefields
    - openff-toolkit >=0.9.0,<0.11.0
    - openmm
    - openmmforcefields >=0.11.2
    - python >=3.6
    - pytorch
    - qcportal >=0.15.0
    - scipy
    - smirnoff99Frosst
    - tqdm

test:
  imports:
    - espaloma
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/choderalab/espaloma
  summary: Extensible Surrogate Potential of Ab initio Learned and Optimized by Message-passing Algorithm 🍹 https://arxiv.org/abs/2010.01196
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - yuanqing-wang
    - ijpulidos
    - jchodera
