{% set name = "espaloma" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/espaloma/archive/{{ version }}.tar.gz
  sha256: f5899c05d0327f0ce531d0f4eddeb6474ec4b1f1812033584a56b1467fd5e471

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dgl >=1.1.2,<=2.3.0
    - matplotlib-base
    - numpy
    - openff-forcefields
    - openff-toolkit >=0.12.0
    - openff-units
    - openmm
    - openmmforcefields >=0.11.2
    - python >={{ python_min }}
    - pytorch
    - qcportal >=0.50
    - scipy
    - smirnoff99Frosst
    - tqdm
    - torchdata <0.10  # https://github.com/pytorch/data/issues/1196#issuecomment-2542528439

test:
  imports:
    - espaloma
  commands:
    - pytest --pyargs espaloma
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/choderalab/espaloma
  summary: Extensible Surrogate Potential of Ab initio Learned and Optimized by Message-passing Algorithm ðŸ¹ https://arxiv.org/abs/2010.01196
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - yuanqing-wang
    - ijpulidos
    - jchodera
